version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_dev.txt
      - run:
          name: Lint
          command: pylint verbcalc
      -run:
          name: Install tree
          command: apt install tree
      -run:
        name: Show tree
        command: tree
      - run:
          name: Run tests
          command: pytest
    resource-class: small

workflows:
  Build_and_test:
    jobs:
      - build-and-test
